# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UniQ | CSS toolkit
email: miguel.melo@uniplaces.com
description: "Uniplaces Internal CSS Toolkit"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uniplaces.github.io/uniplaces-uniq-wiki/" # the base hostname & protocol for your site
twitter_username: miguelbmelo
github_username:  mmelo

# Build settings
markdown: kramdown
